version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /wdl-training/exercise1/HelloWorld.wdl
     testParameterFiles:
         - /wdl-training/exercise1/hello.json
     name: HelloWorld
   - subclass: WDL
     primaryDescriptorPath: /wdl-training/exercise2/solution2/metrics.wdl
     testParameterFiles:
         - /wdl-training/exercise2/metrics.json
     name: metrics
   - subclass: WDL
     primaryDescriptorPath: /wdl-training/exercise3/solution/align_and_metrics.wdl
     testParameterFiles:
         - /wdl-training/exercise3/solution/align_and_metrics.json
     name: align_and_metrics
